### ISSUE TITLE
adding multiple tasks to array and setter method

### ISSUE THREAD

**Issue by christine-hya** [christine-hya/Methods-Challenge#1]
I'm struggling to add multiple tasks to the todos array. Currently it's just adding one task at a time and replacing the previous one.
I also haven't been able to get the setter method to console log 'You must assign a string to your task title' and event.preventDefault() method to work. @xdossantos

**Comment by xdossantos** [comment]
Hi @christine-hya , you need to make the object that is storing the cached list  not encapsulated within a function , basically you need to make sure that the object that you need to persist between the various function calls is in the Global scope (outside of any function) else it is going to be cleared between every function call

**Comment by xdossantos** [comment]
Please can you make a pull request so I can comment on your code line by line ? I see that you have a return on the onclick event

**Comment by christine-hya** [comment]
Thanks @xdossantos 
I have invited you as a collaborator and created a pull request
I added return because the <p> element didn't show previously (it would flicker briefly and then disappear) and when I googled this issue, adding return was suggested as a solution and it worked

**Comment by xdossantos** [comment]
Hi @christine-hya , Thanks 

You need to declare the taskArray in the global scope , and then push a new value to the task array every time a new value needs to be added. Then do a for each loop in the taskArray to populate a list 

![image](https://user-images.githubusercontent.com/39842595/122099819-b963f100-ce12-11eb-8e9c-dcd42c036e26.png)
